Check
SergeGoolchak/PY200 pull request #1
Opened 2020-02-13 20:25 UTC by SergeGoolchak

2020-02-14 11:31 UTC, aeksei requested changes

2020-02-14 11:31 UTC, aeksei commented on Date.py
> -    print(t)
Видимо из-за того, что teach_branch отличается малым количеством строк, то не могу комментировать, прямо по ходу файла.

2020-02-14 11:31 UTC, aeksei commented on Date.py
> -    print(t)
В строках 86-95 воспользуйтесь форматированием строк, чтобы числа сами автоматически дополнялись нулями до ширины в два символа. Вот пример: `f'{self.__day:0>2}'`

Здесь можно почитать, что да как
https://docs.python.org/3/library/string.html#format-specification-mini-language

2020-02-14 11:31 UTC, aeksei commented on Date.py
> -    print(t)
При желании, можно перегрузить `@date.setter`, чтобы он умел принимать дату из трех чисел. 
Тогда в `__init__` можно будет тоже вызывать `date`

2020-02-14 11:31 UTC, aeksei commented on Date.py
> -    print(t)
Вопрос о целесообразности объявления метода `def __rsub__(self, other):`
Я бы его не объявлял, потому что для `Date` - `Date` будет вызываться `__sub__`. А вот например для `int` - `Date` вызовется `__rsub__`, но для `int` нет метода `days_of_date()`

2020-02-14 11:31 UTC, aeksei commented on py200_1_1.py
>  # Тема 1.1 Основы ООП. Понятие класса, объекта. Создание экземпляра класса
Возможно в 241 строке можно обойтись просто `return self.__next`? Тоже самое в 259 и 270

2020-02-14 11:31 UTC, aeksei commented on py200_1_1.py
>  # Тема 1.1 Основы ООП. Понятие класса, объекта. Создание экземпляра класса
Структура вашего списка такая? 
... -> TAIL -> HEAD -> Node0 -> Node1 -> ... -> NodeN -> TAIL -> HEAD -> ...
Т.е HEAD и TAIL не являются узлами самого списка? Иначе говоря HEAD != Node0?

2020-02-14 11:31 UTC, aeksei commented on py200_1_1.py
>  # Тема 1.1 Основы ООП. Понятие класса, объекта. Создание экземпляра класса
Не очень понятно зачем нужны `remove` и `delete` если они делают одно и тоже??
Может тогда `delete` сделать через удаление по индексу?

2020-02-17 11:53 UTC, SergeGoolchak commented on Date.py
> -    print(t)
исправил, но немного в другом формате, Ваш пример почему-то не срабатывал

2020-02-17 11:53 UTC, SergeGoolchak commented on Date.py
> -    print(t)
сделал

2020-02-17 11:53 UTC, SergeGoolchak commented on Date.py
> -    print(t)
убрал, согласен

2020-02-17 11:55 UTC, SergeGoolchak commented on py200_1_1.py
>  # Тема 1.1 Основы ООП. Понятие класса, объекта. Создание экземпляра класса
Head и Tail что-то вроде полей нашего списка, начало и конец, и всегда равны None
241, 259 и 270 поправил

2020-02-17 11:56 UTC, SergeGoolchak commented on py200_1_1.py
>  # Тема 1.1 Основы ООП. Понятие класса, объекта. Создание экземпляра класса
delete теперь удаляет по индексу

2020-02-19 10:49 UTC, aeksei commented on Date.py
> +        return f'{d}.{m}.{self.__year}'
Хорошо. Для f-строк можно использовать ещё так:
`f'{self.day:02}.{self.month:02}.{self.__year}'`

2020-02-19 10:53 UTC, aeksei approved these changes

2020-02-19 10:55 UTC, aeksei commented on Date.py
> -    print(t)
Странно, но имейте в виду, что для f-string тоже можно указывать форматирование

2020-02-19 10:56 UTC, aeksei commented on py200_1_1.py
>  # Тема 1.1 Основы ООП. Понятие класса, объекта. Создание экземпляра класса
Понял, спасибо

2020-02-19 10:57 UTC, aeksei commented on py200_1_1.py
>  # Тема 1.1 Основы ООП. Понятие класса, объекта. Создание экземпляра класса
Есть, увидел

2020-02-19 10:57 UTC, aeksei commented on Date.py
> +        return f'{d}.{m}.{self.__year}'
Странно, по-хорошему должно работать, если работают f-string

2020-02-19 10:58 UTC, aeksei commented
У меня вопросов нет. Если и у вас нет вопросов, можете сливать и закрывать

2020-02-22 12:25 UTC, aeksei commented
Третью лабораторную проверил, вопросов нет

2020-02-25 15:05 UTC, merged